name: Check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    name: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: ["v1", "latest", "edge"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: koppor/cpdfsqueeze-action@${{ matrix.version }}
        with:
          input_file: 'test/example.pdf'
          output_file: 'test/example-small.pdf'
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
