name: Check

on:
  push:
    branches:
      - edge
      - latest
      - v1
    tags:
      - '**'
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      - name: Set up Git repository
        uses: actions/checkout@v5
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: localhost:5000/name/app:latest
      - name: squeeze
        working-directory: test
        run: |
          docker run -v $(pwd):/workdir localhost:5000/name/app:latest example.pdf example-small.pdf
      - name: Archive PDF
        uses: actions/upload-artifact@v4
        with:
          name: example-small.pdf
          path: test/example-small.pdf
  check_v1:
    runs-on: ubuntu-latest
    name: v1
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: koppor/cpdfsqueeze-action@v1
        with:
          input_file: 'test/example.pdf'
          output_file: 'test/example-small.pdf'
  check_latest:
    runs-on: ubuntu-latest
    name: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: koppor/cpdfsqueeze-action@latest
        with:
          input_file: 'test/example.pdf'
          output_file: 'test/example-small.pdf'
  check_edge:
    runs-on: ubuntu-latest
    name: edge
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: koppor/cpdfsqueeze-action@edge
        with:
          input_file: 'test/example.pdf'
          output_file: 'test/example-small.pdf'
